name: TheHelper
main: com.mcmiddleearth.thehelper.TheHelper
version: 1.1.3
website: ${project.url}
authors: [DonoA, q220, aaldim]
description: Helper plugin for Minecraft Middle Earth.
author: DonoA, q220, aaldim
commands:
  helper:
    usage: |
            /helper pm <player>
            /helper forums
            /helper textures
            /helper map
            /helper guide
            /helper rules
            /helper servers
  devinfo:
    usage: |
            /devinfo versions
            /devinfo jobs TSmonitor
            /devinfo jobs TSmonitor <channel>
permissions:
  TheHelper.info:
    default: op
    children:
      TheHelper.info.dev: true
      TheHelper.info.admin: true
  TheHelper.info.dev:
    description: permissions for developers.
    default: op
  TheHelper.info.admin:
    description: permission for staff/admin.
    default: op
