name: TheHelper
main: com.mcmiddleearth.thehelper.TheHelper
version: ${project.version}
website: ${project.url}
authors: [DonoA]
description: Helper plugin for Minecraft Middle Earth.
author: DonoA
commands:
  helper:
    usage: |
            /helper pm <player>
            /helper forums
            /helper textures
  devinfo:
    usage: |
            /devinfo versions
            /devinfo jobs TSmonitor
            /devinfo jobs TSmonitor <channel>